layout: sidebar
style: dark

title: Oksanas Portfolio
description: Oksanas Projects and Interests

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 5
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: oksana-kalytenko-546515119
  # mastodon: your_username
  medium: oxannemiu
  kaggle: oksanakalytenko
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Finance
    web_url: https://github.com/topics/finance
    image_url: https://github.com/google/material-design-icons/raw/f7bd4f25f3764883717c09a1fd867f560c9a9581/png/editor/candlestick_chart/materialiconsoutlined/48dp/2x/outline_candlestick_chart_black_48dp.png
    
  - name: Data Science
    web_url: https://github.com/topics/data-science
    image_url: https://github.com/google/material-design-icons/raw/f7bd4f25f3764883717c09a1fd867f560c9a9581/png/social/psychology/materialiconsoutlined/48dp/2x/outline_psychology_black_48dp.png
    
  - name: Machine Learning
    web_url: https://github.com/topics/machine-learning
    image_url: https://raw.githubusercontent.com/github/explore/558a9d7bbfd1683934210d9500c1e0c8b8c50f77/topics/ai/ai.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png
   

